quarkus.banner.path=banner.txt

quarkus.http.port=7777
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.enable-compression=true
quarkus.http.limits.max-body-size=10M
quarkus.http.compress-media-types=application/json

# Logging levels
quarkus.log.level=INFO
%dev.quarkus.log.console.level=DEBUG
%dev.quarkus.log.category."io.reshapr.proxy".level=DEBUG

# JSON serialization configuration.
quarkus.jackson.serialization-inclusion=non-null

# gRCP clients to the exposition discovery service and the gateway health service.
quarkus.grpc.dev-mode.force-server-start=false
quarkus.grpc.clients."exposition-discovery".host=${reshapr.ctrl.host}
quarkus.grpc.clients."exposition-discovery".port=${reshapr.ctrl.port}
quarkus.grpc.clients."exposition-discovery".plain-text=${reshapr.ctrl.tls.plain-text}
quarkus.grpc.clients."gateway-health".host=${reshapr.ctrl.host}
quarkus.grpc.clients."gateway-health".port=${reshapr.ctrl.port}
quarkus.grpc.clients."gateway-health".plain-text=${reshapr.ctrl.tls.plain-text}

# OpenTelemetry configuration.
%dev.quarkus.otel.enabled=false
%otel.quarkus.otel.enabled=true
%prod.quarkus.otel.enabled=true

quarkus.otel.traces.enabled=true
quarkus.otel.metrics.enabled=true
quarkus.otel.logs.enabled=true
#quarkus.otel.exporter.otlp.endpoint=http://localhost:4317
#quarkus.otel.exporter.otlp.protocol=http/protobuf
#quarkus.otel.exporter.otlp.headers=authorization=Bearer my_secret

# Stores configuration.
quarkus.cache."session-store".type=caffeine
quarkus.cache.caffeine."session-store".initial-capacity=10
quarkus.cache.caffeine."session-store".expire-after-access=300S

quarkus.cache."elicitation-store".type=caffeine
quarkus.cache.caffeine."elicitation-store".initial-capacity=10
quarkus.cache.caffeine."elicitation-store".expire-after-access=120S

# Web Bundler configuration.
quarkus.web-bundler.bundle.app=true
quarkus.web-bundler.bundle.app.key=main
quarkus.web-bundler.bundle.app.qute-tags=true
quarkus.web-bundler.dependencies.auto-import=all

# Native compilation configuration.
quarkus.native.resources.includes=version.properties,templates/**,web/**
quarkus.native.additional-build-args=\
    -H:IncludeLocales=en,\
    --enable-preview,\
    --initialize-at-run-time=io.reshapr.proxy.proxy.ProxyService,\
    --features=io.reshapr.proxy.NativeConfigurationFeature

# Reshapr commons configuration.
graphql.parser.max-characters=100000000
graphql.parser.max-tokens=100000


# Reshapr specific configuration.
# -------------------------------
reshapr.gateway.id=reshapr-gateway-00
reshapr.gateway.labels=env=dev;team=reshapr
reshapr.gateway.fqdns=localhost:7777
reshapr.gateway.mcp.cache.size=1000

# This is the API key used to access this Gateway Admin API.
reshapr.gateway.api.key=${RESHAPR_GATEWAY_API_KEY:cFtltSLYHYZ0lT1zp0S0gq1asg6mMjCUEgHqxgf8R9aUYuCCefrBM2sZZutALEYw6y4EvPaRAQpBs5bjVx2Zp0LqQrHlsz31ZzwVqSIhJDwPY0S44sbDCD5xUeFlcEPOMA4Reugd6GbtalpmUSEu96B37SgjqAaPUqzDw2YeIJuWaP7FJlPlrEg6RQLY5w2piVHXeYrTDFLihQf63IlYbHVIWsCt1LBgQFsgBQjsxXjFtJtVQluAGVlht5m061dp}

reshapr.ctrl.host=localhost
reshapr.ctrl.port=5555
reshapr.ctrl.token=reshapr-my-super-secret-token
reshapr.ctrl.tls.plain-text=${RESHAPR_CTRL_TLS_PLAINTEXT:true}

reshapr.version=${project.version}
reshapr.buildTimestamp=${maven.build.timestamp}