quarkus.banner.path=banner.txt
quarkus.config.locations=version.properties

quarkus.http.host=0.0.0.0
quarkus.http.port=5555
quarkus.http.cors=true
quarkus.http.auth.proactive=false
quarkus.http.enable-compression=true
quarkus.http.compress-media-types=application/json
quarkus.http.limits.max-body-size=10M
quarkus.grpc.server.use-separate-server=false

# Logging levels
quarkus.log.level=INFO
quarkus.log.console.level=DEBUG
quarkus.log.category."io.reshapr.ctrl".level=DEBUG

# JSON serialization configuration.
quarkus.jackson.serialization-inclusion=non-null

# Database + dev service config.
quarkus.datasource.db-kind=postgresql
quarkus.datasource.devservices.port=63663

# Hibernate configuration.
quarkus.hibernate-orm.multitenant=DISCRIMINATOR
quarkus.hibernate-orm.log.sql=false
%dev.quarkus.hibernate-orm.database.generation=none

# Run Flyway migrations automatically
quarkus.flyway.migrate-at-start=true
%dev.quarkus.flyway.locations=db/migration,db/data,db/dev-data
%dev.quarkus.flyway.clean-at-start=true

# TODO: must be changed before going live.
%prod.quarkus.flyway.locations=db/migration,db/data

# JWT configuration for issuing and verifying tokens.
smallrye.jwt.new-token.issuer=https://app.reshapr.io
smallrye.jwt.time-to-live=7200
mp.jwt.verify.issuer=https://app.reshapr.io
mp.jwt.verify.token.age=7200

# TODO: must be changed before going live.
%prod.smallrye.jwt.sign.key.location=keys/jwt-rs256.pem
%prod.mp.jwt.verify.publickey.location=keys/jwt-rs256.pub.pem

# Reshapr commons configuration.
graphql.parser.max-characters=100000000
graphql.parser.max-tokens=100000


# Reshapr specific configuration.
# ------------------------------
# Application mode, can be either "on-premises" or "saas".
reshapr.mode=on-premises
reshapr.ctrl.public-url=${RESHAPR_CTRL_PUBLIC_URL:http://localhost:5555}

# When application in "on-premises", we can define an external IDP for user authentication.
reshapr.authentication.idp.enabled=false
reshapr.authentication.idp.url=http://localhost:8180
reshapr.authentication.idp.realm=reshapr

# This is the API key used to access this application Admin API.
reshapr.ctrl.api.key=${RESHAPR_CTRL_API_KEY:CzBuQ9B0i8qrUQe6WLiDLqR3gv4iCbxvjTJQP0z0CFGQbjgBHPZSusa9d1gZKwwjdoCsJ8ogRwRzc06GipJSjSDkFOy0BSOKvAa2EjU3As9I5UjgizTzxsJAVJIXtdo2xiXHhcry9KeJa0zRhDtGmm8WMujoXrlfj0ChlJKaHZiZsRthd4UHrWkKur9KySXpPFP21H4C0Cq6OgM1rJpvMZ7Jd2ZzeEcd5lKE4PlchHZBVEdu8jYzjQtU50fkOPoR}

# Encryption key used to encrypt sensitive data in the database.
reshapr.encryption.key=${RESHAPR_ENCRYPTION_KEY:my-super-secret-key-32-char-long}

