services:
  web-ui:
    image: lbroudoux/reshapr-ui:nightly
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3333:3333"
    environment:
      - RESHAPR_CTRL_URL=http://control-plane:5555
      # The reshapr control plane API key, e.g. "my-api-key"
      - RESHAPR_ADMIN_API_KEY=CzBuQ9B0i8qrUQe6WLiDLqR3gv4iCbxvjTJQP0z0CFGQbjgBHPZSusa9d1gZKwwjdoCsJ8ogRwRzc06GipJSjSDkFOy0BSOKvAa2EjU3As9I5UjgizTzxsJAVJIXtdo2xiXHhcry9KeJa0zRhDtGmm8WMujoXrlfj0ChlJKaHZiZsRthd4UHrWkKur9KySXpPFP21H4C0Cq6OgM1rJpvMZ7Jd2ZzeEcd5lKE4PlchHZBVEdu8jYzjQtU50fkOPoR
      # The reshapr control plane web-ui application public URL, e.g. "http://localhost:5173"
      - RESHAPR_WEBUI_PUBLIC_URL=http://localhost:5555
      # If you need to restrict access to the web-ui application, you can tune the HOST.
      # - HOST=0.0.0.0